baseURL = 'https://gregarious-hamster-5abffb.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"
[languages]
  [languages.en]
    title = "Ananke"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.tr]
    title = "Ananke TR"
    weight = 2
    contentDir = "content/tr"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  text_color = ""
  author = "Contentrain"
  favicon = ""
  site_logo = "/images/logo.svg"
  description = ""
  recent_posts_number = 3